---
- name: Install OpenJDK
  yum:
    name:
    - "java-{{ open_jdk_version }}-openjdk"
    - maven
  when: ansible_distribution_version == 'RedHat'

- name: instell OpenJDK Debian 
  package: 
    name:
     - openjdk-11-jdk
     - maven
    update_cache: yes
  when: ansible_distribution_version == 'Debian'